language: java

jdk:
  - oraclejdk9

sudo: required

before_script:
  - cd/Users/habib/Documents/workspace/Projet/src

script:
  - mvn test -Ptest-consumer,test-business
  - cd ../../src

notifications:
  email: false
