language: java

sudo: required

services:
  - docker

before_install:
  - cd projet_B4_FR/docker/dev/
  - docker-compose up -d
  - docker ps -a

before_script:
  - cd ../../src

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
       - mvn test -Ptest-consumer,test-business
       - cd ../docker/dev
       - docker-compose stop
       - docker-compose rm -f
       - docker-compose up -d
       - docker ps -a
       - cd ../../src

after_success:
  - mvn --file pom.xml cobertura:cobertura -P test-consumer,test-business
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
